---
- hosts: webservers
  become: yes
  vars:
    javaonubuntu: openjdk-8-jre
    javaonamazon: java-1.8.0-openjdk
  tasks:
  - name: install java on ubuntu16 node
    apt:
     name: "{{ javaonubuntu }}"
     state: present
    when: ansible_os_family== "Debian"

  - name: install java on amazon node
    yum:
     name: "{{ javaonamazon }}"
     state: present
    when: ansible_os_family== "RedHat"      